# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='holding_periods',
        ),
        migrations.AlterField(
            model_name='run',
            name='average',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='winrate',
            field=models.FloatField(null=True),
        ),
    ]
