# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_auto_20160425_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ('stock', 'strategy', 'default', '-profit')},
        ),
        migrations.AddField(
            model_name='run',
            name='average_gain',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='average_loss',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='grossed',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='max_drawdown',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='netted',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='payoff',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='profit_factor',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='risk_factor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='profit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='trades',
            field=models.FloatField(null=True),
        ),
    ]
